// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"
)

type User struct {
	ID             string    `json:"id"`
	Lastname       string    `json:"lastname"`
	Firstname      string    `json:"firstname"`
	HashedPassword string    `json:"hashed_password"`
	Phone          string    `json:"phone"`
	Address        string    `json:"address"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
